# Generated by Django 3.0.5 on 2023-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='stop_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
