# Generated by Django 3.0.5 on 2023-08-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0003_auto_20230824_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='stop_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='titile',
            new_name='title',
        ),
    ]
